# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
   
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

##########

# First, I will generate the fibonacci sequence upto four million.

x = numeric()
i = 0
j = 1

x = append(x, i)
x = append(x, j)

while(1)
{
   l = length(x)
   x = append(x, x[l] + x[l-1])
   if(tail(x, 1) >= 4e6)
      break
}

index = which(x%%2 == 0)
sum(x[index])




